# Generated by Django 5.0.1 on 2024-02-04 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pollsapp', '0002_subchoice_alter_choice_option_alter_choice_question_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subchoice',
            name='suboption',
            field=models.ForeignKey(max_length=150, on_delete=django.db.models.deletion.CASCADE, related_name='subchoices', to='pollsapp.choice'),
        ),
    ]
